"""empty message

Revision ID: 243b92ebb480
Revises: 
Create Date: 2019-05-19 10:06:11.924562

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '243b92ebb480'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=100), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('post', sa.Column('date', sa.DateTime(), nullable=True))
    op.drop_column('post', 'data')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('data', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('post', 'date')
    op.drop_table('comment')
    # ### end Alembic commands ###
