"""empty message

Revision ID: b3613473ae18
Revises: c0d9dbf6c26f
Create Date: 2019-05-20 03:07:56.535343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3613473ae18'
down_revision = 'c0d9dbf6c26f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('second_comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=100), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comment_to_second',
    sa.Column('comment_id', sa.Integer(), nullable=True),
    sa.Column('second_comment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['comment_id'], ['comment.id'], ),
    sa.ForeignKeyConstraint(['second_comment_id'], ['second_comment.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment_to_second')
    op.drop_table('second_comment')
    # ### end Alembic commands ###
